// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[id].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/api/short/url.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Redirectioner.tsx";
import * as $$1 from "./islands/Shortener.tsx";

const manifest = {
  routes: {
    "./routes/[id].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/api/short/url.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Redirectioner.tsx": $$0,
    "./islands/Shortener.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
